# Generated by Django 3.2.12 on 2023-09-12 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalEdu', models.TextField()),
                ('name', models.TextField()),
                ('state', models.TextField()),
                ('enterDate', models.TextField()),
                ('graduateDate', models.TextField()),
                ('passDate', models.TextField()),
                ('region', models.TextField()),
                ('isQualificationExam', models.TextField()),
                ('major', models.TextField()),
                ('isTransfer', models.BooleanField()),
                ('universityType', models.BooleanField()),
                ('universityTime', models.BooleanField()),
                ('extraMajor', models.TextField()),
                ('extraMajorType', models.TextField()),
                ('grade', models.TextField()),
                ('standardGrade', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
