# Generated by Django 3.2.12 on 2023-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='universityTime',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='universityType',
            field=models.TextField(),
        ),
    ]
