# Generated by Django 3.2.12 on 2023-09-23 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20230921_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('licenseName', models.TextField(blank=True, null=True)),
                ('licenseDate', models.TextField(blank=True, null=True)),
                ('licensePlace', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('languageScore', models.TextField(blank=True, null=True)),
                ('languageName', models.TextField(blank=True, null=True)),
                ('languageDate', models.TextField(blank=True, null=True)),
                ('awardName', models.TextField(blank=True, null=True)),
                ('awardDate', models.TextField(blank=True, null=True)),
                ('awardPlace', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
