# Generated by Django 3.2.12 on 2023-09-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='awardDate',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='awardName',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='awardPlace',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='language',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='languageDate',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='languageName',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='languageScore',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='licenseDate',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='licenseName',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='licensePlace',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
