# Generated by Django 3.2.12 on 2023-09-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230923_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='region',
            new_name='startDate',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='startData',
        ),
    ]
