# Generated by Django 3.2.12 on 2023-09-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230923_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='languageRating',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userType',
            field=models.TextField(blank=True, default='신입', null=True),
        ),
    ]
