# Generated by Django 3.2.12 on 2023-10-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.education'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submit',
            name='userInfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userinfo'),
            preserve_default=False,
        ),
    ]
